/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration options for Fast-Context analyzer */
export interface AnalyzerConfig {
  /** Project root directory path */
  projectRoot: string
  /** Languages to analyze (empty = auto-detect all) */
  languages?: Array<string>
  /** File patterns to ignore */
  ignorePatterns?: Array<string>
  /** Enable intelligent caching */
  enableCaching?: boolean
  /** Cache policy (auto, minimal, balanced, adaptive, persistent) */
  cachePolicy?: string
  /** Enable file watching for real-time updates */
  enableWatching?: boolean
  /** Maximum files to analyze (0 = no limit) */
  maxFiles?: number
  /** Enable parallel processing */
  parallelProcessing?: boolean
}
/** Analysis result for Node.js */
export interface AnalysisResultJs {
  /** Total number of files analyzed */
  fileCount: number
  /** Total number of symbols found */
  symbolCount: number
  /** Total number of relationships found */
  relationshipCount: number
  /** Languages detected in the project */
  languages: Array<string>
  /** Analysis duration in milliseconds */
  durationMs: number
  /** Memory usage in MB */
  memoryUsageMb?: number
}
/** Query result for Node.js */
export interface QueryResultJs {
  /** Matching symbols */
  symbols: Array<SymbolInfoJs>
  /** Context information */
  context: ContextInfoJs
  /** Suggestions for the user */
  suggestions: Array<string>
  /** Total results available */
  totalResults: number
}
/** Symbol information for Node.js */
export interface SymbolInfoJs {
  /** Symbol name */
  name: string
  /** Qualified name (full path) */
  qualifiedName: string
  /** Symbol kind (Function, Class, Variable, etc.) */
  kind: string
  /** File path */
  filePath: string
  /** Programming language */
  language: string
  /** Start line (1-based) */
  startLine: number
  /** End line (1-based) */
  endLine: number
  /** Cyclomatic complexity */
  complexity: number
  /** Dependencies (symbols this symbol uses) */
  dependencies: Array<string>
  /** Dependents (symbols that use this symbol) */
  dependents: Array<string>
  /** Signature/declaration */
  signature?: string
  /** Documentation */
  documentation?: string
  /** Symbol modifiers (pub, static, etc.) */
  modifiers: Array<string>
}
/** Context information for Node.js */
export interface ContextInfoJs {
  /** Total symbols in context */
  totalSymbols: number
  /** Files involved */
  filesInvolved: number
  /** Average complexity score */
  complexityScore: number
  /** Architectural patterns detected */
  architecturalPatterns: Array<string>
  /** Potential issues */
  potentialIssues: Array<string>
}
/** Export options for Node.js */
export interface ExportOptionsJs {
  /** Pretty print JSON output */
  prettyPrint?: boolean
  /** Include detailed symbol information */
  includeDetails?: boolean
  /** Include relationships */
  includeRelationships?: boolean
  /** Maximum symbols to export (0 = no limit) */
  maxSymbols?: number
  /** Export format (json, lsp, embedding) */
  format?: string
  /** Enable streaming for large exports */
  streaming?: boolean
}
/** Pagination options for Node.js */
export interface PaginationOptionsJs {
  /** Page number (0-based) */
  page: number
  /** Items per page */
  pageSize: number
  /** Sort field (name, complexity, etc.) */
  sortField?: string
  /** Sort direction (asc, desc) */
  sortDirection?: string
}
/** Filter options for Node.js */
export interface FilterOptionsJs {
  /** Symbol kinds to include */
  symbolKinds?: Array<string>
  /** Languages to include */
  languages?: Array<string>
  /** File patterns to include */
  filePatterns?: Array<string>
  /** Minimum complexity */
  minComplexity?: number
  /** Maximum complexity */
  maxComplexity?: number
  /** Only documented symbols */
  documentedOnly?: boolean
}
/** File change event for Node.js callbacks */
export interface FileChangeEventJs {
  /** Type of change (created, modified, deleted, renamed) */
  changeType: string
  /** Path of the changed file */
  filePath: string
  /** Old path (for rename operations) */
  oldPath?: string
  /** Timestamp of the change */
  timestamp: number
  /** Language of the changed file */
  language?: string
  /** Whether this change affects the analysis */
  affectsAnalysis: boolean
}
/** Batch of file changes for efficient processing */
export interface FileChangeBatchJs {
  /** All changes in this batch */
  changes: Array<FileChangeEventJs>
  /** Total number of changes */
  changeCount: number
  /** Batch timestamp */
  batchTimestamp: number
  /** Whether re-analysis is recommended */
  requiresReanalysis: boolean
  /** Estimated impact level (low, medium, high) */
  impactLevel: string
}
/** Streaming query options for large datasets */
export interface StreamingOptionsJs {
  /** Enable streaming mode */
  enabled: boolean
  /** Chunk size for streaming results */
  chunkSize: number
  /** Include progress callbacks */
  includeProgress?: boolean
  /** Timeout for each chunk in milliseconds */
  chunkTimeoutMs?: number
}
/** Streaming query result chunk */
export interface QueryChunkJs {
  /** Results in this chunk */
  symbols: Array<SymbolInfoJs>
  /** Chunk index (0-based) */
  chunkIndex: number
  /** Total number of chunks */
  totalChunks: number
  /** Whether this is the last chunk */
  isLast: boolean
  /** Progress percentage (0-100) */
  progress: number
  /** Processing time for this chunk in milliseconds */
  processingTimeMs: number
}
/**
 * Utility functions for Fast-Context
 * Get supported languages
 */
export declare function getSupportedLanguages(): Array<string>
/** Detect language from file extension */
export declare function detectLanguage(filePath: string): string | null
/** Check if Fast-Context is properly configured */
export declare function checkConfiguration(): string
/** Get version information */
export declare function getVersion(): string
/** Fast-Context codebase analyzer for Node.js */
export declare class FastContextAnalyzer {
  /** Create a new Fast-Context analyzer */
  constructor(config: AnalyzerConfig)
  /** Analyze the codebase */
  analyze(config?: AnalyzerConfig | undefined | null): AnalysisResultJs
  /** Start file watching for real-time updates with callback support */
  startWatching(callback: (...args: any[]) => any): void
  /** Stop file watching */
  stopWatching(): void
}
