/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration options for Fast-Context analyzer */
export interface AnalyzerConfig {
  /** Project root directory path */
  projectRoot: string
  /** Languages to analyze (empty = auto-detect all) */
  languages?: Array<string>
  /** File patterns to ignore */
  ignorePatterns?: Array<string>
  /** Enable intelligent caching */
  enableCaching?: boolean
  /** Cache policy (auto, minimal, balanced, adaptive, persistent) */
  cachePolicy?: string
  /** Enable file watching for real-time updates */
  enableWatching?: boolean
  /** Maximum files to analyze (0 = no limit) */
  maxFiles?: number
  /** Enable parallel processing */
  parallelProcessing?: boolean
  /** Enable experimental harmonious architecture (default: false for compatibility) */
  enableExperimentalArchitecture?: boolean
}
/** Analysis result for Node.js */
export interface AnalysisResultJs {
  /** Total number of files analyzed */
  fileCount: number
  /** Total number of symbols found */
  symbolCount: number
  /** Total number of relationships found */
  relationshipCount: number
  /** Languages detected in the project */
  languages: Array<string>
  /** Analysis duration in milliseconds */
  durationMs: number
  /** Memory usage in MB (optional) */
  memoryUsageMb?: number
}
/** Query result for Node.js */
export interface QueryResultJs {
  /** Matching symbols */
  symbols: Array<SymbolInfoJs>
  /** Related relationships */
  relationships: Array<RelationshipInfoJs>
  /** Context information */
  context: ContextInfoJs
  /** AI assistant suggestions */
  suggestions: Array<string>
}
/** Symbol information for JavaScript */
export interface SymbolInfoJs {
  /** Symbol name */
  name: string
  /** Symbol kind (function, class, variable, etc.) */
  kind: string
  /** File path where symbol is defined */
  filePath: string
  /** Line number in the file */
  line: number
  /** Column number in the file */
  column: number
  /** Symbol documentation/comments */
  documentation?: string
  /** Symbol signature (for functions/methods) */
  signature?: string
  /** Symbol scope (global, local, etc.) */
  scope: string
  /** Language of the file */
  language: string
}
/** Relationship information for JavaScript */
export interface RelationshipInfoJs {
  /** Source symbol name */
  fromSymbol: string
  /** Target symbol name */
  toSymbol: string
  /** Relationship type (calls, imports, extends, etc.) */
  relationshipType: string
  /** Source file path */
  fromFile: string
  /** Target file path */
  toFile: string
  /** Line number where relationship occurs */
  line: number
  /** Relationship strength/weight */
  weight: number
}
/** Context information for JavaScript */
export interface ContextInfoJs {
  /** Total symbols in the codebase */
  totalSymbols: number
  /** Number of files involved in the query */
  filesInvolved: number
  /** Complexity score of the query result */
  complexityScore: number
  /** Architectural patterns detected */
  architecturalPatterns: Array<string>
  /** Potential issues or improvements */
  potentialIssues: Array<string>
}
/** Export format options */
export interface ExportOptionsJs {
  /** Export format (json, lsp, embeddings) */
  format: string
  /** Output file path (optional) */
  outputPath?: string
  /** Include source code in export */
  includeSource?: boolean
  /** Include documentation in export */
  includeDocs?: boolean
  /** Minify the output */
  minify?: boolean
}
/** File watching event */
export interface FileWatchEvent {
  /** Event type (created, modified, deleted) */
  eventType: string
  /** File path that changed */
  filePath: string
  /** Timestamp of the event */
  timestamp: string
  /** Whether this affects the analysis */
  affectsAnalysis: boolean
}
/** Progress information for chunked analysis */
export interface AnalysisProgress {
  /** Current chunk being processed */
  currentChunk: number
  /** Total number of chunks */
  totalChunks: number
  /** Whether this is the last chunk */
  isLast: boolean
  /** Progress percentage (0-100) */
  progress: number
  /** Processing time for this chunk in milliseconds */
  processingTimeMs: number
}
/** Get the version of the fast-context package */
export declare function getVersion(): string
/** Get list of supported programming languages */
export declare function getSupportedLanguages(): Array<string>
/** Detect the programming language of a file based on its extension */
export declare function detectLanguage(filePath: string): string | null
/** Check if the analyzer configuration is valid */
export declare function checkConfiguration(config?: AnalyzerConfig | undefined | null): string
/** Get system information */
export declare function getSystemInfo(): string
/**
 * Fast-Context codebase analyzer for Node.js
 *
 * THREAD-SAFE ARCHITECTURE: This analyzer now uses proper synchronization
 * for all shared state while maintaining 100% backward compatibility.
 */
export declare class FastContextAnalyzer {
  constructor(config: AnalyzerConfig)
  /** Analyze the codebase and return analysis results */
  analyze(): AnalysisResultJs
  /** Start watching the codebase for changes */
  startWatching(): void
  /** Stop watching the codebase */
  stopWatching(): void
  /** Get the current analysis results */
  getAnalysis(): AnalysisResultJs | null
  /** Find symbols by kind (function, class, variable, etc.) */
  findSymbolsByKind(kind: string): Array<string>
  /** Find symbols in a specific file */
  findSymbolsInFile(filePath: string): Array<string>
  /** Find dependencies of a symbol */
  findDependencies(symbolName: string): Array<string>
  /** Find complex symbols (high complexity) */
  findComplexSymbols(complexityThreshold: number): Array<string>
}
/** Undirected graph implementation */
export declare class RustworkxGraph {
  constructor()
  addNode(weight: string): number
  addEdge(nodeA: number, nodeB: number, weight: number): number | null
  nodeCount(): number
  edgeCount(): number
  removeNode(node: number): boolean
  removeEdge(nodeA: number, nodeB: number): boolean
  hasEdge(nodeA: number, nodeB: number): boolean
  getNodeData(node: number): string | null
  getEdgeData(nodeA: number, nodeB: number): number | null
  neighbors(node: number): Array<number>
  clear(): void
  /**
   * Dijkstra's shortest path algorithm
   * Returns a list of [nodeId, distance] pairs for JavaScript compatibility
   */
  dijkstraShortestPaths(source: number, target?: number | undefined | null): Array<Array<number>>
  /**
   * All-pairs shortest paths using a simple implementation
   * Returns a 2D matrix of shortest distances between all pairs of nodes
   */
  allPairsShortestPaths(): Array<Array<number | undefined | null>>
  /**
   * Betweenness centrality for undirected graphs
   * Returns a list of [nodeId, centrality] pairs
   */
  betweennessCentrality(normalized?: boolean | undefined | null): Array<Array<number>>
  /**
   * Closeness centrality for undirected graphs
   * Returns a list of [nodeId, centrality] pairs
   */
  closenessCentrality(normalized?: boolean | undefined | null): Array<Array<number>>
  /**
   * Check if the undirected graph is bipartite
   * Returns true if the graph can be colored with two colors
   */
  isBipartite(): boolean
  /** Get the number of connected components */
  numberConnectedComponents(): number
  /**
   * Get connected components using a simple DFS approach
   * Returns a list of component IDs for each node
   */
  connectedComponents(): Array<number>
  /**
   * Depth-first search edges from a starting node
   * Returns a list of [source, target] edge pairs in DFS order
   */
  dfsEdges(start: number): Array<Array<number>>
  /**
   * Breadth-first search edges from a starting node
   * Returns a list of [source, target] edge pairs in BFS order
   */
  bfsEdges(start: number): Array<Array<number>>
  /**
   * Depth-first search tree from a starting node
   * Returns a list of nodes in DFS order
   */
  dfsTree(start: number): Array<number>
  /**
   * Breadth-first search tree from a starting node
   * Returns a list of nodes in BFS order
   */
  bfsTree(start: number): Array<number>
}
/** Directed graph implementation */
export declare class RustworkxDiGraph {
  constructor()
  addNode(weight: string): number
  addEdge(nodeA: number, nodeB: number, weight: number): number | null
  nodeCount(): number
  edgeCount(): number
  removeNode(node: number): boolean
  removeEdge(nodeA: number, nodeB: number): boolean
  hasEdge(nodeA: number, nodeB: number): boolean
  getNodeData(node: number): string | null
  getEdgeData(nodeA: number, nodeB: number): number | null
  neighbors(node: number): Array<number>
  predecessors(node: number): Array<number>
  successors(node: number): Array<number>
  clear(): void
  /**
   * Dijkstra's shortest path algorithm for directed graphs
   * Returns a list of [nodeId, distance] pairs for JavaScript compatibility
   */
  dijkstraShortestPaths(source: number, target?: number | undefined | null): Array<Array<number>>
  /**
   * All-pairs shortest paths for directed graphs
   * Returns a 2D matrix of shortest distances between all pairs of nodes
   */
  allPairsShortestPaths(): Array<Array<number | undefined | null>>
  /**
   * Betweenness centrality for directed graphs
   * Returns a list of [nodeId, centrality] pairs
   */
  betweennessCentrality(normalized?: boolean | undefined | null): Array<Array<number>>
  /**
   * Closeness centrality for directed graphs
   * Returns a list of [nodeId, centrality] pairs
   */
  closenessCentrality(normalized?: boolean | undefined | null): Array<Array<number>>
  /**
   * Check if the directed graph is acyclic (DAG)
   * Returns true if the graph contains no cycles
   */
  isDirectedAcyclicGraph(): boolean
  /**
   * Topological sort of the directed graph
   * Returns nodes in topological order, or empty if graph has cycles
   */
  topologicalSort(): Array<number>
  /**
   * Get strongly connected components using Tarjan's algorithm
   * Returns a list of component IDs for each node
   */
  stronglyConnectedComponents(): Array<number>
  /** Get the number of strongly connected components */
  numberStronglyConnectedComponents(): number
  /**
   * Get weakly connected components (treating edges as undirected)
   * Returns a list of component IDs for each node
   */
  weaklyConnectedComponents(): Array<number>
  /**
   * Depth-first search edges from a starting node (directed)
   * Returns a list of [source, target] edge pairs in DFS order
   */
  dfsEdges(start: number): Array<Array<number>>
  /**
   * Breadth-first search edges from a starting node (directed)
   * Returns a list of [source, target] edge pairs in BFS order
   */
  bfsEdges(start: number): Array<Array<number>>
  /**
   * Depth-first search tree from a starting node (directed)
   * Returns a list of nodes in DFS order
   */
  dfsTree(start: number): Array<number>
  /**
   * Breadth-first search tree from a starting node (directed)
   * Returns a list of nodes in BFS order
   */
  bfsTree(start: number): Array<number>
}
