/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration options for Fast-Context analyzer */
export interface AnalyzerConfig {
  /** Project root directory path */
  projectRoot: string
  /** Languages to analyze (empty = auto-detect all) */
  languages?: Array<string>
  /** File patterns to ignore */
  ignorePatterns?: Array<string>
  /** Enable intelligent caching */
  enableCaching?: boolean
  /** Cache policy (auto, minimal, balanced, adaptive, persistent) */
  cachePolicy?: string
  /** Enable file watching for real-time updates */
  enableWatching?: boolean
  /** Maximum files to analyze (0 = no limit) */
  maxFiles?: number
  /** Enable parallel processing */
  parallelProcessing?: boolean
  /** Enable experimental harmonious architecture (default: false for compatibility) */
  enableExperimentalArchitecture?: boolean
}
/** Analysis result for Node.js */
export interface AnalysisResultJs {
  /** Total number of files analyzed */
  fileCount: number
  /** Total number of symbols found */
  symbolCount: number
  /** Total number of relationships found */
  relationshipCount: number
  /** Languages detected in the project */
  languages: Array<string>
  /** Analysis duration in milliseconds */
  durationMs: number
  /** Memory usage in MB (optional) */
  memoryUsageMb?: number
}
/** Query result for Node.js */
export interface QueryResultJs {
  /** Matching symbols */
  symbols: Array<SymbolInfoJs>
  /** Related relationships */
  relationships: Array<RelationshipInfoJs>
  /** Context information */
  context: ContextInfoJs
  /** AI assistant suggestions */
  suggestions: Array<string>
}
/** Symbol information for JavaScript */
export interface SymbolInfoJs {
  /** Symbol name */
  name: string
  /** Symbol kind (function, class, variable, etc.) */
  kind: string
  /** File path where symbol is defined */
  filePath: string
  /** Line number in the file */
  line: number
  /** Column number in the file */
  column: number
  /** Symbol documentation/comments */
  documentation?: string
  /** Symbol signature (for functions/methods) */
  signature?: string
  /** Symbol scope (global, local, etc.) */
  scope: string
  /** Language of the file */
  language: string
}
/** Relationship information for JavaScript */
export interface RelationshipInfoJs {
  /** Source symbol name */
  fromSymbol: string
  /** Target symbol name */
  toSymbol: string
  /** Relationship type (calls, imports, extends, etc.) */
  relationshipType: string
  /** Source file path */
  fromFile: string
  /** Target file path */
  toFile: string
  /** Line number where relationship occurs */
  line: number
  /** Relationship strength/weight */
  weight: number
}
/** Context information for JavaScript */
export interface ContextInfoJs {
  /** Total symbols in the codebase */
  totalSymbols: number
  /** Number of files involved in the query */
  filesInvolved: number
  /** Complexity score of the query result */
  complexityScore: number
  /** Architectural patterns detected */
  architecturalPatterns: Array<string>
  /** Potential issues or improvements */
  potentialIssues: Array<string>
}
/** Export format options */
export interface ExportOptionsJs {
  /** Export format (json, lsp, embeddings) */
  format: string
  /** Output file path (optional) */
  outputPath?: string
  /** Include source code in export */
  includeSource?: boolean
  /** Include documentation in export */
  includeDocs?: boolean
  /** Minify the output */
  minify?: boolean
}
/** File watching event */
export interface FileWatchEvent {
  /** Event type (created, modified, deleted) */
  eventType: string
  /** File path that changed */
  filePath: string
  /** Timestamp of the event */
  timestamp: string
  /** Whether this affects the analysis */
  affectsAnalysis: boolean
}
/** Progress information for chunked analysis */
export interface AnalysisProgress {
  /** Current chunk being processed */
  currentChunk: number
  /** Total number of chunks */
  totalChunks: number
  /** Whether this is the last chunk */
  isLast: boolean
  /** Progress percentage (0-100) */
  progress: number
  /** Processing time for this chunk in milliseconds */
  processingTimeMs: number
}
/** Get the version of the fast-context package */
export declare function getVersion(): string
/** Get list of supported programming languages */
export declare function getSupportedLanguages(): Array<string>

// ========================================
// Auto-generated types from Rust structs
// ========================================

export type FastContextAnalyzerType = Record<string, never>;
/** AnalyzerConfig type definition */
export interface AnalyzerConfig { projectRoot: string, languages: Array<string> | null, ignorePatterns: Array<string> | null, enableCaching: boolean | null, cachePolicy: string | null, enableWatching: boolean | null, maxFiles: number | null, parallelProcessing: boolean | null, }
/** AnalysisResultJs type definition */
export interface AnalysisResultJs { fileCount: number, symbolCount: number, relationshipCount: number, languages: Array<string>, durationMs: number, memoryUsageMb: number | null, }
/** QueryResultJs type definition */
export interface QueryResultJs { symbols: Array<SymbolInfoJs>, context: ContextInfoJs, suggestions: Array<string>, totalResults: number, }
/** SymbolInfoJs type definition */
export interface SymbolInfoJs { name: string, qualifiedName: string, kind: string, filePath: string, language: string, startLine: number, endLine: number, complexity: number, dependencies: Array<string>, dependents: Array<string>, signature: string | null, documentation: string | null, modifiers: Array<string>, }
/** ContextInfoJs type definition */
export interface ContextInfoJs { totalSymbols: number, filesInvolved: number, complexityScore: number, architecturalPatterns: Array<string>, potentialIssues: Array<string>, }
/** ExportOptionsJs type definition */
export interface ExportOptionsJs { prettyPrint: boolean | null, includeDetails: boolean | null, includeRelationships: boolean | null, maxSymbols: number | null, format: string | null, streaming: boolean | null, }
/** PaginationOptionsJs type definition */
export interface PaginationOptionsJs { page: number, pageSize: number, sortField: string | null, sortDirection: string | null, }
/** FilterOptionsJs type definition */
export interface FilterOptionsJs { symbolKinds: Array<string> | null, languages: Array<string> | null, filePatterns: Array<string> | null, minComplexity: number | null, maxComplexity: number | null, documentedOnly: boolean | null, }
/** FileChangeEventJs type definition */
export interface FileChangeEventJs { changeType: string, filePath: string, oldPath: string | null, timestamp: number, language: string | null, affectsAnalysis: boolean, }
/** FileChangeBatchJs type definition */
export interface FileChangeBatchJs { changes: Array<FileChangeEventJs>, changeCount: number, batchTimestamp: number, requiresReanalysis: boolean, impactLevel: string, }
/** StreamingOptionsJs type definition */
export interface StreamingOptionsJs { enabled: boolean, chunkSize: number, includeProgress: boolean | null, chunkTimeoutMs: number | null, }
/** QueryChunkJs type definition */
export interface QueryChunkJs { symbols: Array<SymbolInfoJs>, chunkIndex: number, totalChunks: number, isLast: boolean, progress: number, processingTimeMs: number, }
/** RustworkxGraph type definition */
export interface RustworkxGraph {  }
/** RustworkxDiGraph type definition */
export interface RustworkxDiGraph {  }
