"""Type stubs for Fast-Context Graph Module

This module provides Python bindings for rustworkx graph algorithms,
enabling advanced graph analysis capabilities.
"""

from typing import List, Optional, Tuple, Union
from dataclasses import dataclass


@dataclass
class PathResult:
    """Result from shortest path algorithms."""
    path: List[int]
    distance: float


@dataclass
class CentralityResult:
    """Result from centrality algorithms."""
    node: int
    centrality: float


@dataclass
class ConnectedComponent:
    """Connected component in a graph."""
    nodes: List[int]
    size: int


class PyRustworkxGraph:
    """Python wrapper for rustworkx undirected graph."""
    
    def __init__(self) -> None: ...
    
    @staticmethod
    def with_capacity(nodes: int, edges: int) -> 'PyRustworkxGraph': ...
    
    def add_node(self, weight: Optional[float] = None) -> int: ...
    
    def remove_node(self, node_index: int) -> bool: ...
    
    def add_edge(self, source: int, target: int, weight: Optional[float] = None) -> Optional[int]: ...
    
    def remove_edge(self, source: int, target: int) -> bool: ...
    
    @property
    def node_count(self) -> int: ...
    
    @property
    def edge_count(self) -> int: ...
    
    def is_empty(self) -> bool: ...
    
    def clear(self) -> None: ...
    
    def get_node_weight(self, node_index: int) -> Optional[float]: ...
    
    def set_node_weight(self, node_index: int, weight: float) -> bool: ...
    
    def get_edge_weight(self, source: int, target: int) -> Optional[float]: ...
    
    def set_edge_weight(self, source: int, target: int, weight: float) -> bool: ...
    
    def neighbors(self, node_index: int) -> List[int]: ...
    
    def edges(self, node_index: int) -> List[Tuple[int, int]]: ...
    
    def has_edge(self, source: int, target: int) -> bool: ...
    
    # Graph Algorithms
    def dijkstra_shortest_path(self, source: int, target: int) -> Optional[PathResult]: ...
    
    def floyd_warshall_all_pairs(self) -> List[List[Optional[float]]]: ...
    
    def connected_components(self) -> List[ConnectedComponent]: ...
    
    def betweenness_centrality(self, normalized: bool = True) -> List[CentralityResult]: ...
    
    def closeness_centrality(self, wf_improved: bool = True) -> List[CentralityResult]: ...
    
    def pagerank(self, damping: float = 0.85, max_iterations: int = 100, tolerance: float = 1e-6) -> List[CentralityResult]: ...
    
    def bfs_tree(self, start: int) -> List[int]: ...
    
    def dfs_tree(self, start: int) -> List[int]: ...
    
    def is_directed_acyclic_graph(self) -> bool: ...
    
    def topological_sort(self) -> List[int]: ...
    
    def find_simple_cycles(self) -> List[List[int]]: ...
    
    def density(self) -> float: ...
    
    def clone(self) -> 'PyRustworkxGraph': ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...


class PyRustworkxDiGraph:
    """Python wrapper for rustworkx directed graph."""
    
    def __init__(self) -> None: ...
    
    @staticmethod
    def with_capacity(nodes: int, edges: int) -> 'PyRustworkxDiGraph': ...
    
    def add_node(self, weight: Optional[float] = None) -> int: ...
    
    def remove_node(self, node_index: int) -> bool: ...
    
    def add_edge(self, source: int, target: int, weight: Optional[float] = None) -> Optional[int]: ...
    
    def remove_edge(self, source: int, target: int) -> bool: ...
    
    @property
    def node_count(self) -> int: ...
    
    @property
    def edge_count(self) -> int: ...
    
    def is_empty(self) -> bool: ...
    
    def clear(self) -> None: ...
    
    def successors(self, node_index: int) -> List[int]: ...
    
    def predecessors(self, node_index: int) -> List[int]: ...
    
    def out_edges(self, node_index: int) -> List[Tuple[int, int]]: ...
    
    def in_edges(self, node_index: int) -> List[Tuple[int, int]]: ...
    
    def has_edge(self, source: int, target: int) -> bool: ...
    
    # Directed Graph Specific Algorithms
    def strongly_connected_components(self) -> List[ConnectedComponent]: ...
    
    def weakly_connected_components(self) -> List[ConnectedComponent]: ...
    
    def clone(self) -> 'PyRustworkxDiGraph': ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...


# Convenience aliases
Graph = PyRustworkxGraph
DiGraph = PyRustworkxDiGraph