// Auto-generated TypeScript types for Fast-Context
// Generated by ts-rs from Rust structs - DO NOT EDIT MANUALLY

/** FastContextAnalyzer type definition */
export interface FastContextAnalyzer {  }
/** AnalyzerConfig type definition */
export interface AnalyzerConfig { project_root: string, languages: Array<string> | null, ignore_patterns: Array<string> | null, enable_caching: boolean | null, cache_policy: string | null, enable_watching: boolean | null, max_files: number | null, parallel_processing: boolean | null, }
/** AnalysisResultJs type definition */
export interface AnalysisResultJs { file_count: number, symbol_count: number, relationship_count: number, languages: Array<string>, duration_ms: number, memory_usage_mb: number | null, }
/** QueryResultJs type definition */
export interface QueryResultJs { symbols: Array<SymbolInfoJs>, context: ContextInfoJs, suggestions: Array<string>, total_results: number, }
/** SymbolInfoJs type definition */
export interface SymbolInfoJs { name: string, qualified_name: string, kind: string, file_path: string, language: string, start_line: number, end_line: number, complexity: number, dependencies: Array<string>, dependents: Array<string>, signature: string | null, documentation: string | null, modifiers: Array<string>, }
/** ContextInfoJs type definition */
export interface ContextInfoJs { total_symbols: number, files_involved: number, complexity_score: number, architectural_patterns: Array<string>, potential_issues: Array<string>, }
/** ExportOptionsJs type definition */
export interface ExportOptionsJs { pretty_print: boolean | null, include_details: boolean | null, include_relationships: boolean | null, max_symbols: number | null, format: string | null, streaming: boolean | null, }
/** PaginationOptionsJs type definition */
export interface PaginationOptionsJs { page: number, page_size: number, sort_field: string | null, sort_direction: string | null, }
/** FilterOptionsJs type definition */
export interface FilterOptionsJs { symbol_kinds: Array<string> | null, languages: Array<string> | null, file_patterns: Array<string> | null, min_complexity: number | null, max_complexity: number | null, documented_only: boolean | null, }
/** FileChangeEventJs type definition */
export interface FileChangeEventJs { change_type: string, file_path: string, old_path: string | null, timestamp: number, language: string | null, affects_analysis: boolean, }
/** FileChangeBatchJs type definition */
export interface FileChangeBatchJs { changes: Array<FileChangeEventJs>, change_count: number, batch_timestamp: number, requires_reanalysis: boolean, impact_level: string, }
/** StreamingOptionsJs type definition */
export interface StreamingOptionsJs { enabled: boolean, chunk_size: number, include_progress: boolean | null, chunk_timeout_ms: number | null, }
/** QueryChunkJs type definition */
export interface QueryChunkJs { symbols: Array<SymbolInfoJs>, chunk_index: number, total_chunks: number, is_last: boolean, progress: number, processing_time_ms: number, }
/** RustworkxGraph type definition */
export interface RustworkxGraph {  }
/** RustworkxDiGraph type definition */
export interface RustworkxDiGraph {  }
